Update testcase.yml

diff --git a/.github/workflows/testcase.yml b/.github/workflows/testcase.yml
--- a/.github/workflows/testcase.yml
+++ b/.github/workflows/testcase.yml
@@ -21,12 +21,17 @@ jobs:
       - name: Set Up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '16' # Specify Node.js version
+          node-version: '16'
           cache: 'npm'
 
       # Install dependencies
       - name: Install Dependencies
-        run: npm ci
+        run: |
+          if [ ! -f package-lock.json ]; then
+            echo "package-lock.json not found. Exiting.";
+            exit 1;
+          fi
+          npm ci
         env:
           CI: true
 
